version: "3"
services:
  nginx:
     restart: always
     container_name: nginx
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     ports:
       - "80:80"
     build:
       context: ./nginx
#       dockerfile: Dockerfile
  # postgres:
  #   image: postgres:10.5
  #   restart: always
  #   container_name: postgres
  #   # env_file:
  #   #   - ./server/.env
  #   # Postgres ports should never be exposed in production
  #   # uncomment the ports only for development reasons
  #   ports:
  #     - "5432:5432"
  #   # environment:
  #     # 'POSTGRES_PASSWORD' and 'POSTGRES_USER' are inside './server/.env'
  #     # POSTGRES_DB: "scs"
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go
    restart: always